# Generated by Django 4.0.4 on 2022-05-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_athlete'),
        ('event', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Weight')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('medal', models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze'), ('NA', 'NA')], max_length=6, verbose_name='Medal')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event')),
            ],
        ),
    ]
