# Generated by Django 4.0.4 on 2022-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_athleteevent_athlete_alter_athleteevent_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteevent',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Weight'),
        ),
    ]
