# Generated by Django 4.0.4 on 2022-05-10 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, verbose_name='Sex')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='athlete.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Athlete',
                'verbose_name_plural': 'Athletes',
            },
        ),
    ]
