# Generated by Django 4.0.4 on 2022-05-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete', '0002_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athlete.team', verbose_name='Team'),
        ),
    ]
